### ISSUE TITLE
RecognitionLongAudio  each run creates a aws s3 key 

### ISSUE THREAD

**Issue by irubtsov** [TikhonP/yandex-speechkit-lib-python#8]
**Describe the bug**
When using the **RecognitionLongAudio** method, each run creates a aws s3 key 
```
url_aws_credentials = 'https://iam.api.cloud.yandex.net/iam/aws-compatibility/v1/accessKeys'
data_aws_credentials = {'description': aws_credentials_description, 'serviceAccountId': service_account_id}
answer = requests.post(url_aws_credentials, headers=self._headers, json=data_aws_credentials)
answer = answer.json()
        self._s3 = self._init_aws(
            aws_access_key_id=answer.get('accessKey', {}).get('keyId'),
            aws_secret_access_key=answer.get('secret'),
            region_name=aws_region_name,
        )

```

**Additional context**
I think it's worth putting the credentials for   _init_aws(**kwargs)  into class

**Comment by tikhonp** [comment]
On last commit (`5a7ba4748ddcdc0dde8ce631f3da600c5fad2405`) I added new optional arguments into init of `RecognitionLongAudio` and staticmethod `get_aws_credentials` you can look at [example](https://github.com/TikhonP/yandex-speechkit-lib-python/blob/master/examples/long_audio_recognition.py) how to use it.
