### ISSUE TITLE
NameError: name 'staticmethodq' is not defined

### ISSUE THREAD

**Issue by migelbd** [TikhonP/yandex-speechkit-lib-python#9]
**Describe the bug**
NameError
name 'staticmethodq' is not defined

in version 2.2.0 from PyPI

**Screenshots**
![CleanShot 2023-03-28 at 19 40 49](https://user-images.githubusercontent.com/5161410/228309573-c50355e3-5755-47c4-94c0-75ac14d84301.png)

**Comment by sk-zanzibar** [comment]
Same error

**Comment by tikhonp** [comment]
Ah sorry, I'm a goofball. This typo appeared only in the version from the PyPI, I'll fix it now

**Comment by tikhonp** [comment]
I fixed it in [version 2.2.1](https://pypi.org/project/speechkit/2.2.1/). Thank you for your feedback! : )
